version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Executing unit tests - `pwd`"
      - echo Update npm to latest
      - npm install -g npm@latest
      - cd deployment && chmod +x ./run-unit-tests.sh && ./run-unit-tests.sh
      - echo "Installing dependencies and executing unit tests completed `date`"
  build:
    commands:
      - echo "Installing dependencies for build tooling `date`"
      - chmod +x ./build-s3-dist-env.sh && ./build-s3-dist-env.sh 
      - echo "Starting build `date` in `pwd`"
      - chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
      - echo "Build completed `date`"
  post_build:
    commands:
      - echo "Retrieving next stage buildspec `date` in `pwd`"
      - aws s3 cp s3://${SOLUTIONS_BUILD_ASSETS_BUCKET:-solutions-build-assets}/changelog-spec.yml ../buildspec.yml
      - echo "Retrieving next stage buildspec complete"
      - echo "Post build completed on `date`"

artifacts:
  files:
    - deployment/**/*
    - source/**/*
    - .gitignore
    - sonar-project.properties
    - buildspec.yml
    - CHANGELOG.md
    - .cfnnag_*
